// Predefined Quests & Starter Packs Library for EmberQuest

export const PREDEFINED_CATEGORIES = [
  'ALL',
  'STRENGTH',
  'INTELLECT',
  'DISCIPLINE',
  'VITALITY',
  'CHARISMA',
  'EPIC BOSS',
];

export const PREDEFINED_QUESTS = [
  // ─── DISCIPLINE ───
  {
    id: 'pomodoro_sprint',
    category: 'DISCIPLINE',
    title: '25-Min Pomodoro Sprint',
    description: 'Single-task laser focus on primary battle objective with zero tab switching',
    attribute: 'Discipline',
    difficulty: 'MEDIUM',
    timer: 25,
    recurrence: 'NONE',
    icon: '🍅',
    color: '#fbbf24',
    badge: 'Focus',
  },
  {
    id: 'eat_the_frog',
    category: 'DISCIPLINE',
    title: 'Slay The Dreaded Task (Eat the Frog)',
    description: 'Conquer the single most avoided or daunting task on your backlog first thing',
    attribute: 'Discipline',
    difficulty: 'HARD',
    timer: 30,
    recurrence: 'NONE',
    icon: '🐸',
    color: '#fbbf24',
    badge: 'Willpower',
  },
  {
    id: 'inbox_zero',
    category: 'DISCIPLINE',
    title: 'Sanctuary Reset: Inbox & Tab Zero',
    description: 'Triage pending messages, clear browser tabs, and declutter your digital desk',
    attribute: 'Discipline',
    difficulty: 'EASY',
    timer: 15,
    recurrence: 'DAILY',
    icon: '🧹',
    color: '#fbbf24',
    badge: 'Order',
  },
  {
    id: 'evening_reflection',
    category: 'DISCIPLINE',
    title: 'Evening Chronicle & Daily Plan',
    description: 'Review victories, log learnings, and prepare tomorrow’s 3 priority quests',
    attribute: 'Discipline',
    difficulty: 'TRIVIAL',
    timer: 10,
    recurrence: 'DAILY',
    icon: '📜',
    color: '#fbbf24',
    badge: 'Ritual',
  },

  // ─── INTELLECT ───
  {
    id: 'deep_coding_flow',
    category: 'INTELLECT',
    title: 'Deep Coding Flow Session',
    description: 'Uninterrupted deep focus building features, debugging, and shipping code',
    attribute: 'Intellect',
    difficulty: 'HARD',
    timer: 45,
    recurrence: 'NONE',
    icon: '💻',
    color: '#60a5fa',
    badge: 'Builder',
  },
  {
    id: 'read_30_pages',
    category: 'INTELLECT',
    title: 'Absorb 30 Pages of Wisdom',
    description: 'Read high-signal literature, non-fiction books, or engineering research',
    attribute: 'Intellect',
    difficulty: 'MEDIUM',
    timer: 25,
    recurrence: 'DAILY',
    icon: '📖',
    color: '#60a5fa',
    badge: 'Scholar',
  },
  {
    id: 'algorithm_duel',
    category: 'INTELLECT',
    title: 'Algorithm & Logic Duel',
    description: 'Solve 1-2 medium algorithmic challenges or system design blueprints',
    attribute: 'Intellect',
    difficulty: 'MEDIUM',
    timer: 35,
    recurrence: 'NONE',
    icon: '♟️',
    color: '#60a5fa',
    badge: 'Logic',
  },
  {
    id: 'architecture_deep_dive',
    category: 'INTELLECT',
    title: 'System Architecture Deep Dive',
    description: 'Study RFCs, architectural diagrams, or technical whitepapers',
    attribute: 'Intellect',
    difficulty: 'HARD',
    timer: 50,
    recurrence: 'NONE',
    icon: '🏛️',
    color: '#60a5fa',
    badge: 'Mastery',
  },

  // ─── STRENGTH ───
  {
    id: 'morning_iron_workout',
    category: 'STRENGTH',
    title: 'Morning Iron Workout',
    description: 'Heavy resistance, barbell, or dumbbell strength training to forge raw power',
    attribute: 'Strength',
    difficulty: 'HARD',
    timer: 45,
    recurrence: 'NONE',
    icon: '🏋️',
    color: '#ef4444',
    badge: 'Iron',
  },
  {
    id: '5k_cardio_run',
    category: 'STRENGTH',
    title: '5K Realm Endurance Run',
    description: 'High-cadence cardiovascular run or stair climber stamina test',
    attribute: 'Strength',
    difficulty: 'MEDIUM',
    timer: 30,
    recurrence: 'NONE',
    icon: '🏃',
    color: '#ef4444',
    badge: 'Stamina',
  },
  {
    id: '100_pushup_challenge',
    category: 'STRENGTH',
    title: 'Century Challenge: 100 Pushups',
    description: 'Perform 100 crisp form pushups broken into sets of 20 throughout the day',
    attribute: 'Strength',
    difficulty: 'MEDIUM',
    timer: 15,
    recurrence: 'DAILY',
    icon: '🥊',
    color: '#ef4444',
    badge: 'Bodyweight',
  },
  {
    id: 'leg_day_calamity',
    category: 'STRENGTH',
    title: 'Titan Leg Day Crucible',
    description: 'Heavy squats, Romanian deadlifts, and walking lunges to build pillars of steel',
    attribute: 'Strength',
    difficulty: 'EPIC',
    timer: 60,
    recurrence: 'NONE',
    icon: '⚡',
    color: '#ef4444',
    badge: 'Titan',
  },

  // ─── VITALITY ───
  {
    id: 'hydration_reset',
    category: 'VITALITY',
    title: 'Hydration & Posture Reset',
    description: 'Drink 500ml fresh water, decompress spine, and practice 2 min box breathing',
    attribute: 'Vitality',
    difficulty: 'TRIVIAL',
    timer: 15,
    recurrence: 'DAILY',
    icon: '💧',
    color: '#34d399',
    badge: 'Recharge',
  },
  {
    id: '10k_steps_march',
    category: 'VITALITY',
    title: '10,000 Step Realm March',
    description: 'Accumulate 10,000 brisk steps to maintain cardiovascular circulation',
    attribute: 'Vitality',
    difficulty: 'MEDIUM',
    timer: 0,
    recurrence: 'DAILY',
    icon: '🌿',
    color: '#34d399',
    badge: 'Endurance',
  },
  {
    id: 'cold_awakening',
    category: 'VITALITY',
    title: 'Cold Awakening Ritual',
    description: 'Finish morning shower with 2 minutes of ice-cold water to trigger dopamine',
    attribute: 'Vitality',
    difficulty: 'EASY',
    timer: 5,
    recurrence: 'DAILY',
    icon: '❄️',
    color: '#34d399',
    badge: 'Nerve',
  },
  {
    id: '8hr_restorative_sleep',
    category: 'VITALITY',
    title: '8-Hour Restorative Slumber',
    description: 'Achieve 8 hours of uninterrupted deep sleep in a dark room; screens off early',
    attribute: 'Vitality',
    difficulty: 'MEDIUM',
    timer: 0,
    recurrence: 'DAILY',
    icon: '🌙',
    color: '#34d399',
    badge: 'Recovery',
  },

  // ─── CHARISMA ───
  {
    id: 'public_speaking_pitch',
    category: 'CHARISMA',
    title: 'Public Speaking & Pitch Rehearsal',
    description: 'Practice and record presentation aloud, refining cadence, posture, and tone',
    attribute: 'Charisma',
    difficulty: 'HARD',
    timer: 45,
    recurrence: 'NONE',
    icon: '🎙️',
    color: '#c084fc',
    badge: 'Voice',
  },
  {
    id: 'gratitude_allies',
    category: 'CHARISMA',
    title: 'Express Gratitude to 3 Allies',
    description: 'Send 3 sincere, thoughtful notes of appreciation to colleagues or friends',
    attribute: 'Charisma',
    difficulty: 'EASY',
    timer: 10,
    recurrence: 'NONE',
    icon: '💌',
    color: '#c084fc',
    badge: 'Empathy',
  },
  {
    id: 'network_expansion',
    category: 'CHARISMA',
    title: 'Connect with Realm Pioneer',
    description: 'Reach out to or have a conversation with someone doing inspiring work',
    attribute: 'Charisma',
    difficulty: 'MEDIUM',
    timer: 20,
    recurrence: 'NONE',
    icon: '🤝',
    color: '#c084fc',
    badge: 'Network',
  },

  // ─── EPIC BOSS ───
  {
    id: 'ship_production_mvp',
    category: 'EPIC BOSS',
    title: 'Dragon Slayer: Ship to Production',
    description: 'Deploy code to live servers, launch feature publicly, and share with real users',
    attribute: 'Intellect',
    difficulty: 'EPIC',
    timer: 60,
    recurrence: 'NONE',
    icon: '🐉',
    color: '#ef4444',
    badge: 'Boss',
  },
  {
    id: 'deep_sanctuary_cleanse',
    category: 'EPIC BOSS',
    title: 'Citadel Cleanse: Total Space Reset',
    description: 'Deep clean living quarters, do laundry, take out waste, and reset desk',
    attribute: 'Discipline',
    difficulty: 'HARD',
    timer: 45,
    recurrence: 'NONE',
    icon: '🏰',
    color: '#fbbf24',
    badge: 'Sanctuary',
  },
];

export const STARTER_PACKS = [
  {
    id: 'adventurer_starter',
    title: 'Novice Adventurer Pack',
    description: 'The three essential daily rituals for building momentum and hero discipline.',
    icon: '⚔️',
    questIds: ['pomodoro_sprint', 'hydration_reset', 'morning_iron_workout'],
    tag: 'Recommended for Beginners',
  },
  {
    id: 'code_wizard',
    title: 'Arcane Developer Pack',
    description: 'Engineered for developers: deep code flow, system architecture, and clear desk.',
    icon: '🔮',
    questIds: ['deep_coding_flow', 'read_30_pages', 'inbox_zero'],
    tag: 'Deep Work Protocol',
  },
  {
    id: 'titan_warrior',
    title: 'Titan Crucible Pack',
    description: 'Physical prowess and iron endurance: heavy lifting, 10k steps, and cold reset.',
    icon: '🛡️',
    questIds: ['morning_iron_workout', '10k_steps_march', 'cold_awakening'],
    tag: 'Physical Mastery',
  },
];
